<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonAddfoto</name>
   <tag></tag>
   <elementGuidId>257164f6-76c5-4f12-afa2-a7e68abe36a0</elementGuidId>
   <imagePath>C:\Users\rafki\git\automationTest\Screenshots\testAvatar.png</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[1]/div/div[2]/div/button</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>C:\Users\rafki\git\automationTest\Screenshots\testAvatar.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
